### ISSUE TITLE
Remove unnecessary github actions

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/desci#40]
## 🚀 Feature Request

When performing minor merges (and dependabot ones are an example) there is no need to rerun the desci action, generating the pdf: if the master paper/ folder diff with the merging one is none, do not run that action.

See [here](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) for the best way forward.

**Comment by matteoettam09** [comment]
Can we disable github actions when the push is done by dependabot @Caceresenzo?

**Comment by matteoettam09** [comment]
See [here](https://www.meziantou.net/executing-github-actions-jobs-or-steps-only-when-specific-files-change.htm)

**Comment by Caceresenzo** [comment]
Dependabot should always trigger the github actions since a library will be updated.
Checking for a breaking change is mandatory to avoid accidental breaks.

**Comment by matteoettam09** [comment]
Ok, here is all I wanted to do, otherwise dependabot does it twice:

https://github.com/crunchdao/desci/commit/c1a45dd3187e36f61206079877aacda36564af5a
