### ISSUE TITLE
The links in the PDF are not visible enough

### ISSUE THREAD

**Issue by jeheran** [crunchdao/desci#43]
## 🐛 Bug Report

The links in the PDF are not visible enough. Underlining or highlighting may help the reader to navigate the paper metadata.

### Screenshots

E.g. 1:
![image](https://user-images.githubusercontent.com/39467268/187729159-ba1c3fb8-42c8-4c41-80b9-4ce7ca957ff4.png)

E.g. 2:
![image](https://user-images.githubusercontent.com/39467268/187729350-80d689eb-69c2-4976-af02-21b48185c15f.png)

**Comment by matteoettam09** [comment]
Done [here](https://github.com/crunchdao/desci/commit/a72e9c13a46ce4bca95d6b19684ba6639556f847)

Closing issue.
